"""
doc_registry.py — hand-written registry of the source PDFs.

doc_id values for documents already in the old KB are kept identical so chunk
provenance stays comparable across rebuilds. `system` drives the FSDS/FDSS/WSP
tags; `default_oem` stamps single-OEM manuals so rag.py's OEM boost works.
Nothing is inferred from filenames (some are WhatsApp exports).

Routing + provenance fields (added for the multi-manual scale-up — used by
retrieval routing, supersession/recency, and clause-level citation):
  coach_type : list of applicable coaches — LHB / ICF / Vande Bharat /
               Amrit Bharat / common. Drives cross-manual disambiguation.
  subsystem  : finer than `system` (e.g. "fire detection", "wheel slide
               protection", later "brakes", "bogie", "electrical", "HVAC").
  issue_date : ISO 'YYYY-MM-DD' (or 'YYYY-MM') of issue/revision — reformatted
               from `source`, NOT invented. Newest wins on a value conflict.
  revision   : document revision label as printed.
  letter_no  : circular / SMI / manual reference number, for citations.
  supersedes : doc_ids whose values this document overrides. Leave [] unless the
               supersession is explicit in the document — a mechanical engineer
               should confirm before adding, as it changes which value is quoted.
"""
import os
from urllib.parse import quote

DOCUMENTS_ROOT = os.path.join(os.path.dirname(__file__), "..", "Documents")

# Public base URL of the object-storage bucket (Cloudflare R2 / Supabase) that
# holds the source PDFs — set at build time so `download_url()` can turn each
# doc into a clickable citation. Empty (unset) => no links, citations stay text.
# Trailing slash is stripped; the per-doc key is the URL-encoded PDF basename.
PDF_BUCKET_BASE = os.environ.get("PDF_BUCKET_BASE", "").rstrip("/")

# Applied by `full()` so every consumer sees the complete schema even for rows
# that omit an optional routing/provenance field.
_DEFAULTS = {
    "coach_type": [],
    "subsystem": "",
    "issue_date": "",
    "revision": "",
    "letter_no": "",
    "supersedes": [],
    # force_ocr: the PDF's native text is corrupted (bad font encoding), so ignore
    # it and build the doc purely from OCR. Set True only for such docs.
    "force_ocr": False,
    # download_url: filled by build_kb via download_url(entry) so each chunk
    # carries a link to its source PDF. Empty when PDF_BUCKET_BASE is unset.
    "download_url": "",
}

REGISTRY = [
    {
        "doc_id": "IRCAMTECH_FSDS_FDSS_Vol2",
        "path": os.path.join("Fire system", "Manual", "ICF LHB FDSS  FSDS Maintenance Manual Volume-2.pdf"),
        "doc_type": "maintenance_manual",
        "title": "Maintenance Manual for FSDS and FDSS Volume-2 (LHB & ICF Coaches)",
        "source": "IRCAMTECH/GWL/M/FSDS/FDSS/1.0, October 2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["LHB", "ICF"],
        "subsystem": "fire detection",
        "issue_date": "2024-10",
        "revision": "1.0",
        "letter_no": "IRCAMTECH/GWL/M/FSDS/FDSS/1.0",
    },
    {
        "doc_id": "IRCAMTECH_FSDS_FDSS_Vol1",
        "path": os.path.join("Fire system", "Manual", "VB  for FDSS FSDS Maintenance Manual Volume-1.pdf"),
        "doc_type": "maintenance_manual",
        "title": "Maintenance Manual for FSDS and FDSS Volume-1 (Vande Bharat & Amrit Bharat Coaches)",
        "source": "IRCAMTECH/GWL/M/FSDS/FDSS/1.0, October 2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["Vande Bharat", "Amrit Bharat"],
        "subsystem": "fire detection",
        "issue_date": "2024-10",
        "revision": "1.0",
        "letter_no": "IRCAMTECH/GWL/M/FSDS/FDSS/1.0",
    },
    {
        "doc_id": "MC_ACF_MCB_2A_Standardization",
        "path": os.path.join("Fire system","MC ACF Fire detection AC_Standardise MCB 2A_1 10 24.pdf"),
        "doc_type": "circular",
        "title": "RDSO Circular: Standardization of 2A MCB in FSDS System",
        "source": "RDSO MC/ACF/Fire Detection/AC, 01.10.2024 & 12.08.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "2024-10-01",
        "revision": "",
        "letter_no": "RDSO MC/ACF/Fire Detection/AC",
        "supersedes": [],
    },
    {
        "doc_id": "MC_ACF_FSDS_Guideline",
        "path": os.path.join("Fire system","MC ACF Fire Detection AC_PED EN HM Proj_Guideline FSDS.pdf"),
        "doc_type": "circular",
        "title": "RDSO Guideline: FSDS Fire Detection System (PED EN HM Project)",
        "source": "RDSO MC/ACF/Fire Detection/AC",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "",
        "revision": "",
        "letter_no": "RDSO MC/ACF/Fire Detection/AC",
    },
    {
        "doc_id": "FSDS_Dead_Attach_Operationalisation",
        "path": os.path.join("Fire system","Operationalisation of FSDS during dead attach movement of coaches dated 06.06.2024.pdf"),
        "doc_type": "circular",
        "title": "Operationalisation of FSDS during Dead Attach Movement of Coaches",
        "source": "Railway circular, 06.06.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "2024-06-06",
        "revision": "",
        "letter_no": "",
    },
    {
        "doc_id": "RDSO_Fire_Properties_Testing",
        "path": os.path.join("Fire system","Testing of Fire Properties for coach furnishing materials dated 24.06.2022.pdf"),
        "doc_type": "circular",
        "title": "RDSO: Testing of Fire Properties for Coach Furnishing Materials",
        "source": "RDSO Lucknow MC/Testing, 24.06.2022",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire properties testing",
        "issue_date": "2022-06-24",
        "revision": "",
        "letter_no": "RDSO Lucknow MC/Testing",
    },
    {
        "doc_id": "IRCAMTECH_WSP_Handbook",
        "path": os.path.join("wsp", "1469096933210-WSP Handbook CAMTECH.pdf"),
        "doc_type": "maintenance_manual",
        "title": "Handbook on Wheel Slide Protection Device (WSP)",
        "source": "IRCAMTECH/2011/Mech/WSP/1.0, August 2011",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2011-08",
        "revision": "1.0",
        "letter_no": "IRCAMTECH/2011/Mech/WSP/1.0",
    },
    {
        "doc_id": "Faiveley_AEF_G2_WSP",
        "path": os.path.join("wsp", "Faiveley FT.pdf"),
        "doc_type": "oem_manual",
        "title": "AEF G2 WSP Maintenance/Use Manual - LHB Coaches Indian Railways",
        "source": "FT0027800-003 E00 MUM Rev A01, 26/02/2019, Faiveley/Wabtec",
        "system": "WSP",
        "default_oem": "FAIVELEY",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-02-26",
        "revision": "A01",
        "letter_no": "FT0027800-003 E00 MUM",
    },
    {
        "doc_id": "KB_CMG_WSP_Presentation",
        "path": os.path.join("wsp", "KB WSP full.pdf"),
        "doc_type": "oem_presentation",
        "title": "Knorr-Bremse WSP Device - 14th CMG Meeting Presentation (LHB Coaches)",
        "source": "Knorr-Bremse Group, 14th CMG Meeting PURI, September 2014, Rajiv Agarwal",
        "system": "WSP",
        "default_oem": "KNORR BREMSE",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2014-09",
        "revision": "",
        "letter_no": "",
    },
    {
        "doc_id": "Escorts_Kubota_WSP_GUI",
        "path": os.path.join("wsp", "DOC-20240502-WA0048.pdf"),
        "doc_type": "oem_manual",
        "title": "Escorts Kubota WSP GUI Application Rev 4.1 - User Manual",
        "source": "Escorts Kubota Limited (Railway Equipment Division), 2024",
        "system": "WSP",
        "default_oem": "ESCORTS KUBOTA",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2024",
        "revision": "4.1",
        "letter_no": "",
    },

    # ── Fire-system circulars / instructions added 2026-07 ───────────────────
    # Titles/letter_no for SCANNED docs are best-effort until OCR confirms the
    # cover page — a mechanical engineer should verify the (*) fields.
    {
        "doc_id": "FDSS_Pantry_Power_Functionality_2024",
        "path": os.path.join("Fire system", "Functionality of automatic FDSS fitted in Pantry & Power cars dated 06.06.2024.pdf"),
        "doc_type": "circular",
        "title": "Functionality of Automatic FDSS fitted in Pantry & Power Cars",
        "source": "Railway circular, 06.06.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "2024-06-06",
        "revision": "",
        "letter_no": "",
    },
    {
        "doc_id": "FDSS_Guidelines_22001_Amend1_2024",
        "path": os.path.join("Fire system", "Guidlines of FDSS as per 22001_Amendment 1_PED EnHM_30 11 24.pdf"),
        "doc_type": "circular",
        "title": "RDSO Guidelines for FDSS Upgradation — Amendment-1 of IS/RDSO/CG/S/22001 (Pantry Cars & Generator-cum-Brake Vans, ICF & LHB)",
        "source": "RDSO MC/ACF/Fire Supprn/PC, 29.11.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["ICF", "LHB"],
        "subsystem": "fire detection",
        "issue_date": "2024-11-29",
        "revision": "Amendment 1",
        "letter_no": "MC/ACF/Fire Supprn/PC",
    },
    {
        "doc_id": "FDSS_PowerSupply_GaribRath",
        "path": os.path.join("Fire system", "letter to ZRs_Power supply for Garib Rath.pdf"),
        "doc_type": "circular",
        "title": "Letter to ZRs: Power Supply for FDSS in Garib Rath Coaches",
        "source": "RDSO MC/ACF/Fire Detection/AC (letter to ZRs)",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "",
        "revision": "",
        "letter_no": "MC/ACF/Fire Detection/AC",
    },
    {
        "doc_id": "MC_ACF_Impl_Modification_2025",
        "path": os.path.join("Fire system", "MC ACF Fire Detection AC to PCMEs_Implementation modification dated 04.02.2025.pdf"),
        "doc_type": "circular",
        "title": "RDSO to PCMEs: Implementation Modification of FSDS Fire Detection",
        "source": "RDSO MC/ACF/Fire Detection/AC, 04.02.2025",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "2025-02-04",
        "revision": "",
        "letter_no": "MC/ACF/Fire Detection/AC",
        # newest FSDS instruction here — recency tie-break makes it govern on
        # value conflicts; add explicit supersedes[] once the change is confirmed.
        "supersedes": [],
        # native text is corrupted-font mojibake (verified via KB audit) — OCR it
        "force_ocr": True,
    },
    {
        "doc_id": "MC_ACF_PowerSupply_MCB",
        "path": os.path.join("Fire system", "MC ACF Fire Detection AC_PCMEs_Power supply MCB.pdf"),
        "doc_type": "circular",
        "title": "RDSO to PCMEs: Power Supply MCB for FSDS Fire Detection",
        "source": "RDSO MC/ACF/Fire Detection/AC",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "",
        "revision": "",
        "letter_no": "MC/ACF/Fire Detection/AC",
    },
    {
        "doc_id": "FSDS_Overheated_Wire_Test_2024",
        "path": os.path.join("Fire system", "over heated wire test for FSDS fitted in IR AC Coaches dated 13.06.2024.pdf"),
        "doc_type": "circular",
        "title": "Over-heated Wire Test for FSDS fitted in IR AC Coaches",
        "source": "Railway circular, 13.06.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire detection",
        "issue_date": "2024-06-13",
        "revision": "",
        "letter_no": "",
    },
    {
        "doc_id": "FSDS_Compliance_RDSO2008CG04_2024",
        "path": os.path.join("Fire system", "5. Compliance of RDSO specification no. RDSO2008CG-04 and guidelines for FSDS system dated 27.11.2024.pdf"),
        "doc_type": "circular",
        "title": "RDSO: Compliance of Specification RDSO/2008/CG-04 & FSDS Guidelines (MCB / control supply from TB X1 of SBC)",
        "source": "RDSO MC/ACF/Fire Detection/AC, 27.11.2024 (spec RDSO/2008/CG-04)",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "fire detection",
        "issue_date": "2024-11-27",
        "revision": "",
        "letter_no": "MC/ACF/Fire Detection/AC",
    },
    {
        "doc_id": "FSDS_Aerosol_Pin_Removal_2023",
        "path": os.path.join("Fire system", "Aerosol Pin removal guidelines 07-02-2023.pdf"),
        "doc_type": "circular",
        "title": "Aerosol Pin Removal Guidelines (FSDS Aerosol Generator)",
        "source": "RDSO EL/7.1.108/MSSBC, 07.02.2023",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "fire suppression",
        "issue_date": "2023-02-07",
        "revision": "",
        "letter_no": "EL/7.1.108/MSSBC",
    },
    {
        "doc_id": "CAI_RCF_MECH_LHB_064",
        "path": os.path.join("Fire system", "CAI_RCF_MECH_LHB_064.pdf"),
        "doc_type": "maintenance_instruction",
        "title": "RCF Coach Alteration Instruction CAI/RCF/MECH/LHB/064: Locking of Isolating Cock, Aspiration Fire Detection (LHB AC Coaches)",
        "source": "RCF Kapurthala CAI/RCF/MECH/LHB/064 (No. MD46111), 22.05.2024",
        "system": "FSDS",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "fire detection",
        "issue_date": "2024-05-22",
        "revision": "",
        "letter_no": "CAI/RCF/MECH/LHB/064",
    },

    # ── RDSO WSP instruction letters (Documents/wsp/Instruction letter) ───────
    # All 13 are scans whose *native* text layer is a lossy scanner-OCR: it
    # duplicates whole pages (doc 6: 32% repeated shingles), detaches table
    # values from their column headers (doc 8's AEFG2 choke table), garbles the
    # very numbers these letters exist to fix ("0.9 to l.4mm" / "0.9 to 1,4mm"
    # in the air-gap letter), and leaves the vector-drawn wiring annexures of
    # RDSO_WSP_Wrong_Connections_2019 at ~10 chars/page. So every one of them is
    # force_ocr — re-transcribed by Gemini vision rather than trusted. See
    # SME-verify note below: (*) fields are read off the scan, not a text layer.
    {
        "doc_id": "RDSO_WSP_AirGap_SpeedSensor_2012",
        "path": os.path.join("wsp", "Instruction letter",
                             "20-Air Gap setting between phonic wheel and WSP speed sensor dated 15_02_2012.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Air Gap Setting between Phonic Wheel and WSP Speed Sensor — standardised 0.9–1.4 mm for both makes",
        "source": "RDSO MC/LHB/Brake, 15.02.2012",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2012-02-15",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_FT_Equipment_Approval_2016",
        "path": os.path.join("wsp", "Instruction letter",
                             "23-Wheel Slide protection (WSP) Equipment of FT make for LHB Coaches dated-17_03_2016.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Wheel Slide Protection (WSP) Equipment of Faiveley Transport make for LHB Coaches (AEFG2 approval)",
        "source": "RDSO MC/LHB/Brake, 17.03.2016",
        "system": "WSP",
        "default_oem": "FAIVELEY",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2016-03-17",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Performance_Feedback_2017",
        "path": os.path.join("wsp", "Instruction letter",
                             "27-Performance of WSP in LHB Coaches dated 12_07_2017.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Performance of WSP in LHB Coaches — failure-reporting proforma (Annexure-I)",
        "source": "RDSO MC/LHB/Brake, 12.07.2017",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2017-07-12",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Maintenance_2018",
        "path": os.path.join("wsp", "Instruction letter",
                             "30- Maintenance of WSP of LHB Coaches dated-15_01_2018.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Maintenance of WSP of LHB Coaches — reiterated maintenance instructions",
        "source": "RDSO MC/LHB/Brake, 15.01.2018",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2018-01-15",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Choke_Sizes_DumpValve_2018",
        "path": os.path.join("wsp", "Instruction letter",
                             "6- Modification in choke sizes of Dump Valves of WSP system in LHB coaches dated-19_11_2018.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Modification in Choke Sizes of Dump Valves of WSP System in LHB Coaches (charging choke 9 mm, exhaust 'No Choke')",
        "source": "RDSO MC/LHB/Brake, 19.11.2018 (ref CRR report RDSO/CG/CRR-18002)",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2018-11-19",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        # NOT marked as superseded by the 2019 choke letters: the 15.04.2019
        # letter they cite is not in Documents/, so the supersession chain can't
        # be read end-to-end here. Recency tie-break already prefers the 2019
        # letters on a value clash. SME to confirm before hard-coding it.
        "supersedes": [],
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Revised_Wiring_Scheme_2019",
        "path": os.path.join("wsp", "Instruction letter",
                             "7- Revised wiring scheme for WSP system of LHB Coaches_ dated-27_02_2019.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Revised Wiring Scheme for WSP System of LHB Coaches — modified junction box drawing CG-19005 Alt.1 (6 JB → 4 JB)",
        "source": "RDSO MC/LHB/Brake, 27.02.2019",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-02-27",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Choke_Sizes_AEFG2_2019",
        "path": os.path.join("wsp", "Instruction letter",
                             "8-Choke sizes for AEFG2 model of WSP (Ms Faiveley Transport make) for LHB Coaches_ dated 10_06_19.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Choke Sizes for AEFG2 Model of WSP (Faiveley Transport make) for LHB Coaches — Dump Valve DV12",
        "source": "RDSO MC/LHB/Brake, 10.06.2019 (ref even no. 15.04.2019)",
        "system": "WSP",
        "default_oem": "FAIVELEY",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-06-10",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "supersedes": [],
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_SpeedSensor_Numbering_2019",
        "path": os.path.join("wsp", "Instruction letter",
                             "9-Standardization of numbering for speed sensors in LHB dated 25_07_19.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Standardization of Numbering for WSP Speed Sensors in LHB Coaches (SS-1..SS-4, axle numbering from brake panel)",
        "source": "RDSO MC/LHB/Brake, 25.07.2019",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-07-25",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Electrical_Integrity_2019",
        "path": os.path.join("wsp", "Instruction letter",
                             "12-Ensuring Integrity of electrical connections of WSP System dated 27.09.2019.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Ensuring Integrity of Electrical Connections of WSP System (intermittent short-circuit / broken-cable faults)",
        "source": "RDSO MC/LHB/Brake, 27.09.2019",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-09-27",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Wrong_Connections_2019",
        "path": os.path.join("wsp", "Instruction letter",
                             "13-Wheel Shelling-Wrong electrical connections in WSP system of LHB Coaches. dated 17.12.2019.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Wheel Shelling — Wrong Electrical Connections in WSP System of LHB Coaches (sleep mode after 15–20 min; wiring diagrams Annexure A–F)",
        "source": "RDSO MC/LHB/Brake, 17.12.2019 (19th CMG)",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2019-12-17",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_SpeedSensor_FS01A_2020",
        "path": os.path.join("wsp", "Instruction letter",
                             "39-Issue of procurement of Speed Sensor FS01A Ms Knorr-Bremse make WSP system of LHB dated-04_03_2020.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Procurement of Speed Sensor FS01A (Knorr-Bremse make) for WSP System of LHB Coaches — Part No. STN 31450/250A18U, UIC 541-05 Appendix F3",
        "source": "RDSO MC/LHB/Brake, 04.03.2020",
        "system": "WSP",
        "default_oem": "KNORR BREMSE",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2020-03-04",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_CB12_Card_Config_2024",
        "path": os.path.join("wsp", "Instruction letter",
                             "Letter to PUS_WSP CB-12 Card Configure_dated 03.05.2024.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO to PUs: Configuring of CB-12 Card in Knorr-Bremse (KBI) make WSP — required for error/event data logging",
        "source": "RDSO MC/LHB/Brake, 03.05.2024",
        "system": "WSP",
        "default_oem": "KNORR BREMSE",
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2024-05-03",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        "force_ocr": True,
    },
    {
        "doc_id": "RDSO_WSP_Junction_Box_Installation_2024",
        "path": os.path.join("wsp", "Instruction letter",
                             "RDSO letter dated 21.05.2024_Junction Box.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Standardised Installation of WSP Junction Box & Speed Sensor in LHB Coaches (installation method, cable routing)",
        "source": "RDSO MC/LHB/Brake, 21.05.2024 (ref 27.02.2019 & 08.05.2024)",
        "system": "WSP",
        "default_oem": None,
        "coach_type": ["LHB"],
        "subsystem": "wheel slide protection",
        "issue_date": "2024-05-21",
        "revision": "",
        "letter_no": "MC/LHB/Brake",
        # newest WSP instruction in the KB — recency tie-break makes it govern on
        # installation-method conflicts with the 2019 wiring-scheme letter.
        "supersedes": [],
        "force_ocr": True,
    },
    # ================================================================
    # Vande Bharat — Wave 1: wheels / bearings (CTRB) / bogie springs.
    # Scaffolded by ingest/scaffold_registry.py, then field-verified against the
    # PDFs. Dates come from each letter's own "Date:" field where it is legible;
    # where the letter says "Date: As signed" or its scan mangles the year, the
    # filename date is used and noted. `supersedes` is left [] pending SME
    # sign-off even where the chain is obvious — see the header rule.
    # ================================================================
    {
        "doc_id": "VB_Wheel_Reprofiling_2024",
        "path": os.path.join("Vande Bharat",
                             "2024_01_11 Re-profiling of wheels of vande bharat trains (1).pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Re-profiling of Wheels of Vande Bharat Coaches (criteria and periodicity)",
        "source": "RDSO MC/EMU/WTA, 11.01.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2024-01-11",
        "letter_no": "MC/EMU/WTA",
    },
    {
        "doc_id": "VB_Wheel_Diameter_Difference_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_01_29_Difference in wheel diameter for Vande Bharat Trains.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Permissible Difference in Wheel Diameter for Vande Bharat Trains",
        "source": "RDSO MC/EMU/WTA, 29.01.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2025-01-29",
        "letter_no": "MC/EMU/WTA",
    },
    {
        "doc_id": "VB_Wheel_Marking_Update_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_05_23 letter to ZRs reg updated marking on wheels.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Updating of Marking/Stamping Particulars on Wheels (per IRS R-19/93 Pt-II Rev.6, Sketch-92114 alt.11)",
        "source": "RDSO MC/WA/Genl, 23.05.2025 (ref 29.05.2024 & 13.09.2024)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["common"],
        "subsystem": "wheels",
        "issue_date": "2025-05-23",
        "letter_no": "MC/WA/Genl",
    },
    {
        # Same letter_no and date as the entry above but a different document —
        # citations must be told apart by title, not by reference number.
        "doc_id": "VB_Wheel_KLW_Serial_Format_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_05_23_letter to ZRs reg marking on wheels (1).pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Serial Number Format for M/s KLW Wheels in CMM Portal for Vande Bharat Coaches",
        "source": "RDSO MC/WA/Genl, 23.05.2025 (to CRSE/WCR Jabalpur)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2025-05-23",
        "letter_no": "MC/WA/Genl",
    },
    {
        "doc_id": "VB_Wheel_Reprofiling_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_05_28 Letter to ZRs for re-profiling of VB wheels.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO to Zonal Railways: Re-profiling of Wheels of Vande Bharat Coaches",
        "source": "RDSO MC/EMU/WTA, 28.05.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2025-05-28",
        "letter_no": "MC/EMU/WTA",
    },
    {
        "doc_id": "VB_CTRB_Bearing_Maintenance_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_07_04_letter to ZRs on maintenance of Vande Bharat Bearings.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: CTRB Failures in Vande Bharat Coaches — Maintenance of Bearings",
        "source": "RDSO MC/WA/Genl, 04.07.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-07-04",
        "letter_no": "MC/WA/Genl",
    },
    {
        "doc_id": "VB_CTRB_SKF_Withholding_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_07_17_Withholding SKF CTRB in Vande Bharat.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Withholding of SKF make CTRB in Vande Bharat Coaches",
        "source": "RDSO MC/WA/Genl, 17.07.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-07-17",
        "letter_no": "MC/WA/Genl",
    },
    {
        "doc_id": "VB_CTRB_Guidelines_2025",
        "path": os.path.join("Vande Bharat",
                             "Guidelines for Vande Bharat CTRB issues 11082025 (1).pdf"),
        "doc_type": "circular",
        "title": "RDSO Guidelines for Controlling Vande Bharat CTRB Failures",
        "source": "RDSO MC/CTRB/Defect, 11.08.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-08-11",
        "letter_no": "MC/CTRB/Defect",
    },
    {
        "doc_id": "VB_CTRB_Central_Sleeve_Lubricant_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_09_10_Alternative Lubricant  Rust preventive Paste for Central Sleeves in VB Coaches (2).pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Alternative Lubricant / Rust Preventive Paste for Central Sleeves in Vande Bharat Coaches",
        "source": "RDSO MC/CTRB/Defect, 10.09.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-09-10",
        "letter_no": "MC/CTRB/Defect",
    },
    {
        # The letter's own date field reads "Date: As signed"; the filename date is
        # used. Its Ref line cites 17.07.2025, which a naive parse would have taken.
        "doc_id": "VB_CTRB_SKF_Replacement_SS2_2025",
        "path": os.path.join("Vande Bharat",
                             "2025_10_25_Replacement of SKF Bearing during SS2 Schedule.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO to ICF: Replacement of SKF make CTRBs during SS-2 Schedule in Vande Bharat Coaches",
        "source": "RDSO MC/WA/Genl, 25.10.2025 (ref 17.07.2025, 26.09.2025 & 14.10.2025)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-10-25",
        "letter_no": "MC/WA/Genl",
    },
    {
        "doc_id": "VB_CTRB_Refurbishment_Periodicity_2024",
        "path": os.path.join("Vande Bharat", "CTRB Refurbishment schedule.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Periodicity of Refurbishment of CTRBs",
        "source": "RDSO MC/CTRB/General, 09.07.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2024-07-09",
        "letter_no": "MC/CTRB/General",
    },
    {
        "doc_id": "VB_CTRB_Refurbishment_RCNK_Reply_2025",
        "path": os.path.join("Vande Bharat", "CTRB reply RCNK Jhansi.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO to RCNK Jhansi: Periodicity of Refurbishment of CTRB (Timken make, SS-1 schedule)",
        "source": "RDSO MC/CTRB/VB/Defects, 05.08.2025 (ref RCNK/JHS 29.07.2025 & MC/CTRB/General 09.07.2024)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2025-08-05",
        "letter_no": "MC/CTRB/VB/Defects",
    },
    {
        "doc_id": "VB_CTRB_Vibration_Temperature_Monitoring_2026",
        "path": os.path.join("Vande Bharat",
                             "Monitoring of vibration and temperature of CTRB in existing Vande Bharat Trains.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Monitoring of Vibration and Temperature of CTRB in Existing Vande Bharat Trains",
        "source": "RDSO MC/CTRB/VB/Defects, 06.03.2026 (ref MC/WA/Genl 04.07.2025 & MC/CTRB/Defect 11.08.2025)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bearings",
        "issue_date": "2026-03-06",
        "letter_no": "MC/CTRB/VB/Defects",
    },
    {
        # Letterhead is mojibake ("GovErnment", "2A24"); date taken from the
        # legible "Dated: 31.07.2024" and confirmed by the filename suffix.
        "doc_id": "VB_Vibration_Report_SS1_2024",
        "path": os.path.join("Vande Bharat",
                             "2024-08-08-Report on Vibrations in Vande Bharat Train-31.07.24.pdf"),
        "doc_type": "report",
        "title": "RDSO Report: Vibration in Vande Bharat Coaches after SS-1 Schedule",
        "source": "RDSO MC/TSBD, 31.07.2024 (circulated 08.08.2024)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bogie",
        "issue_date": "2024-07-31",
        "letter_no": "MC/TSBD",
    },
    {
        "doc_id": "VB_Wheel_Vibration_After_SS1_2025",
        "path": os.path.join("Vande Bharat",
                             "25_09_2025 Vibration in VB wheels after SS1.pdf"),
        "doc_type": "report",
        "title": "Vibration in Vande Bharat Wheels after SS-1 Schedule",
        "source": "25.09.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2025-09-25",
        "letter_no": "",
    },
    {
        "doc_id": "VB_Primary_Coil_Spring_Failure_2024",
        "path": os.path.join("Vande Bharat",
                             "MC-TS-BD dated 15 01 2024_to Railways Fialure of VB Springs.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Failure of Primary Coil Springs in Vande Bharat Trains",
        "source": "RDSO MC/TS/BD, 15.01.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "bogie",
        "issue_date": "2024-01-15",
        "letter_no": "MC/TS/BD",
    },
    {
        # Filed under Documents/Vande Bharat/ but it is an ICF-design document, and
        # labelling it Vande Bharat would let an ICF wheel size be quoted for a VB
        # coach. `system` is left unset for the same reason — it is a wheel circular,
        # not part of the VB trainset family.
        "doc_id": "ICF_Wheel_Last_Shop_Issue_Size_2020",
        "path": os.path.join("Vande Bharat", "MC-WA-Genl. dated 23.10.2020.pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Last Shop Issue Size of Wheels of ICF Design BG Main Line Coaches",
        "source": "RDSO MC/WA/Genl, 23.10.2020",
        "system": None,
        "default_oem": None,
        "coach_type": ["ICF"],
        "subsystem": "wheels",
        "issue_date": "2020-10-23",
        "letter_no": "MC/WA/Genl",
        "force_ocr": True,   # letterhead and body are both mojibake
    },

    # ================================================================
    # Vande Bharat — Wave 2: maintenance schedules, en-route troubleshooting,
    # and the VB/SMI/E electrical + air-suspension instruction series.
    # The SMI letters put only "VB/SMI/E/nn Dated: dd.mm.yyyy" in the text layer;
    # the body is a full-page scan, so titles here come from the filename and the
    # SMI number, and are re-verified against OCR text after ingest/ocr_gemini.py.
    # Excluded from this folder: the Make-in-India negative-list circular
    # (MC/Misc/Update 27.01.2023) — procurement policy, not maintenance knowledge.
    # ================================================================
    {
        "doc_id": "VB_Shop_Schedule_SS1_SS2_Report_2025",
        "path": os.path.join("Vande Bharat",
                             "Report on Shop Schedule Activities for Vande Bharat Trainset (Ver_ 2).pdf"),
        "doc_type": "report",
        "title": "Railway Board Committee Report: Maintenance Activities for SS-1 and SS-2 Schedules of Vande Bharat Rakes",
        "source": "Railway Board, New Delhi, 20.08.2025 (ref CAMTECH IRCAMTECH/GWL/M/Trainset/SS-I&SS-II dt 24.07.2025)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "maintenance schedule",
        "issue_date": "2025-08-20",
        "letter_no": "Railway Board E-Office No. 3450123",
    },
    {
        # Subsystem deliberately left empty: this manual spans every subsystem, so
        # a label would let _subsystem_factor demote it on most queries.
        "doc_id": "VB_SMI_Enroute_Troubleshooting_18",
        "path": os.path.join("Vande Bharat", "En-route trouble shooting procedure VB.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "En-route Trouble Shooting Procedure for Vande Bharat Trainset (VB/SMI/E/18)",
        "source": "ICF VB/SMI/E/18",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "",
        "issue_date": "",
        "letter_no": "VB/SMI/E/18",
    },
    {
        "doc_id": "VB_IWWP_Worn_Wheel_Profile_2023",
        "path": os.path.join("Vande Bharat", "2023_12_29 IWWP for Vande Bharat Coaches (1).pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Use of Intermediate Worn Wheel Profile (IWWP) for Vande Bharat Coaches",
        "source": "RDSO MC/EMU/WTA, 29.12.2023",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "wheels",
        "issue_date": "2023-12-29",
        "letter_no": "MC/EMU/WTA",
    },
    {
        "doc_id": "VB_AS_Leakage_Test_2023",
        "path": os.path.join("Vande Bharat",
                             "MC TS BD dated 27 12 2023 to PUs and ZR for AS leakage test in VB coaches (2).pdf"),
        "doc_type": "instruction_letter",
        "title": "RDSO: Air Suspension System of Vande Bharat Trains (leakage test)",
        "source": "RDSO MC/TS/BD, 27.12.2023",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "air suspension",
        "issue_date": "2023-12-27",
        "letter_no": "MC/TS/BD",
    },
    {
        "doc_id": "VB_AS_Leakage_ZR_Instruction_2024",
        "path": os.path.join("Vande Bharat",
                             "2024-09-19-Instruction to ZR_leakage VB2 L no SV AS VB dated 08 08 2024.pdf"),
        "doc_type": "instruction_letter",
        "title": "Attention to Arrest Leakages in Air Suspension System of Vande Bharat Coaches (probable leakage sources, RKMP depot findings)",
        "source": "08.08.2024, circulated 19.09.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "air suspension",
        "issue_date": "2024-08-08",
        "letter_no": "SV.AS.VB",
    },
    {
        "doc_id": "VB_ASDIS_Protocol_2024",
        "path": os.path.join("Vande Bharat",
                             "2024-09-19-SV AS VB dated 07 08 2024 to ZRs and PUs for ASDIS_Protocol.pdf"),
        "doc_type": "instruction_letter",
        "title": "Air Spring Deflation Indication System (ASDIS) in Vande Bharat Coaches",
        "source": "07.08.2024, circulated 19.09.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "air suspension",
        "issue_date": "2024-08-07",
        "letter_no": "SV.AS.VB",
    },
    {
        "doc_id": "VB_SMI_ADCR_Operating_2023",
        "path": os.path.join("Vande Bharat", "Instruction of ADCR VB_SMI_E_01_07.07.2023 (1).pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/01: Operating Procedure and Instructions for ADCR in Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/01, 07.07.2023",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "doors",
        "issue_date": "2023-07-07",
        "letter_no": "VB/SMI/E/01",
    },
    {
        "doc_id": "VB_SMI_VCB_Check_Drive_2024",
        "path": os.path.join("Vande Bharat", "Drive to check VCB VB_SMI_E_02_12.03.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/02: Special Drive to Check VCB TRIP Train Line (Basic Unit Level) for Vande Bharat Train Set",
        "source": "ICF VB/SMI/E/02, 12.03.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2024-03-12",
        "letter_no": "VB/SMI/E/02",
        "force_ocr": True,   # 12 of 13 pages are scans; text layer is header-only
    },
    {
        "doc_id": "VB_SMI_Power_Connector_Failure_2024",
        "path": os.path.join("Vande Bharat",
                             "failure of power connectors letter VB_SMI_E_03_13.06.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/03: Incidence of Failure of Power Connectors in Vande Bharat Trains",
        "source": "ICF VB/SMI/E/03, 13.06.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2024-06-13",
        "letter_no": "VB/SMI/E/03",
    },
    {
        "doc_id": "VB_SMI_Battery_Deep_Discharge_2024",
        "path": os.path.join("Vande Bharat",
                             "Battery deep discharge instructions VB_SMI_E_04_07.09.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/04: Instruction Procedure to Avoid Deep Discharge of Battery System in Vande Bharat Trainset Coaches",
        "source": "ICF VB/SMI/E/04, 07.09.2024 (ref M/s Medha MAE675UV2:ICF:4650:2024 dt 23.08.2024)",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2024-09-07",
        "letter_no": "VB/SMI/E/04",
    },
    {
        "doc_id": "VB_SMI_Shielding_Connections_2024",
        "path": os.path.join("Vande Bharat",
                             "Modification in shielding connections VB_SMI_E_05_29.10.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/05: Modification in Shielding Connections in Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/05, 29.10.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2024-10-29",
        "letter_no": "VB/SMI/E/05",
    },
    {
        "doc_id": "VB_SMI_VCB_Isolation_2024",
        "path": os.path.join("Vande Bharat", "VCB isolation VB_SMI_E_06_06.11.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/06: VCB Isolation Procedure in Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/06, 06.11.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2024-11-06",
        "letter_no": "VB/SMI/E/06",
    },
    {
        "doc_id": "VB_SMI_Winter_Preparedness_2024",
        "path": os.path.join("Vande Bharat",
                             "winter preparedness drive .VB_SMI_E_07_14.11.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/07: Winter Preparedness Drive for Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/07, 14.11.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "maintenance schedule",
        "issue_date": "2024-11-14",
        "letter_no": "VB/SMI/E/07",
        "force_ocr": True,   # single page, 3 extractable tokens
    },
    {
        "doc_id": "VB_SMI_CPA_RMPU_2024",
        "path": os.path.join("Vande Bharat", "CPA in RMPUs .VB_SMI_E_08_20.11.2024.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/08: CPA (Condenser/Compressor Protection) in RMPUs of Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/08, 20.11.2024",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "HVAC",
        "issue_date": "2024-11-20",
        "letter_no": "VB/SMI/E/08",
    },
    {
        "doc_id": "VB_SMI_Light_Dimming_2025",
        "path": os.path.join("Vande Bharat", "Procedure for dimming of light in VB.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/12: Procedure for Dimming of Light in Vande Bharat Coaches",
        "source": "ICF VB/SMI/E/12, 08.02.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2025-02-08",
        "letter_no": "VB/SMI/E/12",
        "force_ocr": True,   # 3 of 3 pages are scans, 3 extractable tokens
    },
    {
        "doc_id": "VB_SMI_Traction_Prohibition_Isolation_2025",
        "path": os.path.join("Vande Bharat",
                             "Revised isolation procedure for traction phohibition in trainset.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/13: Revised Isolation Procedure for Traction Prohibition in Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/13, 11.03.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2025-03-11",
        "letter_no": "VB/SMI/E/13",
    },
    {
        "doc_id": "VB_SMI_Summer_Preparedness_2025",
        "path": os.path.join("Vande Bharat", "Instruction on summer preparedness.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/15: Instruction on Summer Preparedness for Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/15, 26.03.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "maintenance schedule",
        "issue_date": "2025-03-26",
        "letter_no": "VB/SMI/E/15",
        "force_ocr": True,   # 3 of 3 pages are scans, 3 extractable tokens
    },
    {
        # 2 pages are the ICF instruction; the other 26 are M/s TE Connectivity's
        # HVJL Installation & Maintenance Manual, each page stamped "CLASS 2 -
        # CONFIDENTIAL / TE Proprietary & Confidential Information". Source PDFs are
        # published to a public anyone-with-link R2 bucket, so this was raised with
        # the owner before ingest; they confirmed normal ingest + publish.
        "doc_id": "VB_SMI_Jumper_Cable_Inspection_2025",
        "path": os.path.join("Vande Bharat",
                             "cycle check inpsetion of jumper cables VB_SMI_E_17_29.04.2025.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/17: Cycle Check Inspection of Jumper Cables in Vande Bharat Trainset (incl. TE Connectivity HVJL manual)",
        "source": "ICF VB/SMI/E/17, 29.04.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2025-04-29",
        "letter_no": "VB/SMI/E/17",
    },
    {
        "doc_id": "VB_SMI_Digital_TW_IV_Coupler_2025",
        "path": os.path.join("Vande Bharat",
                             "19.VB_SMI_E_use of digital tw for IV coupler 19_02.07.2025.pdf"),
        "doc_type": "special_maintenance_instruction",
        "title": "VB/SMI/E/19: Use of Digital Torque Wrench for Inter-Vehicle (IV) Coupler in Vande Bharat Trainset",
        "source": "ICF VB/SMI/E/19, 02.07.2025",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "2025-07-02",
        "letter_no": "VB/SMI/E/19",
    },
    {
        "doc_id": "VB_CPA_VCD_Foot_Switch_Removal",
        "path": os.path.join("Vande Bharat", "Removal of VCD foot operated switch.pdf"),
        "doc_type": "instruction_letter",
        "title": "Implementation of CPA in Vande Bharat Trainset Rakes — Removal of VCD Foot Operated Switch",
        "source": "ICF",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "",
        "letter_no": "",
    },
    {
        "doc_id": "VB_Master_Controller_SB_Failure_ICF9",
        "path": os.path.join("Vande Bharat",
                             "Failure of SB due to master controller malfuncitoning (ICF-9).pdf"),
        "doc_type": "instruction_letter",
        "title": "Failure of Vande Bharat Express due to Master Controller Malfunctioning (ICF-9)",
        "source": "ICF-9",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": "electrical",
        "issue_date": "",
        "letter_no": "",
    },

    # ================================================================
    # Vande Bharat — Wave 3: ICF Coach Alteration Instructions (CAI).
    # Every cover page is a full-page scan whose text layer is the scanner's own
    # OCR ("CAI No 8,-2025t16", "Date: 1614.2025", "ICF/QIVS/MDtV/File/F0 1 5"),
    # which is why is_scanned_page drives OCR here rather than any char-count rule.
    # Dates are the year from the CAI number unless the cover was legible enough to
    # read in full; they are re-verified against OCR text after ingest.
    # ================================================================
    {
        "doc_id": "VB_CAI_Drain_Hole_2023",
        "path": os.path.join("Vande Bharat", 'CAI A drain hole provision-2023-06.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2023/06: CAI for Drain hole provision in sidewall of Vande Bharat Coaches",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2023/06",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2023',
        "letter_no": "CAI A-2023/06",
    },
    {
        "doc_id": "VB_CAI_Footrest_Extension_2023",
        "path": os.path.join("Vande Bharat", 'CAI A footrest extension-2023-12.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2023/12: Footrest Extension (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2023/12",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2023',
        "letter_no": "CAI A-2023/12",
    },
    {
        "doc_id": "VB_CAI_Improved_Sealing_2023",
        "path": os.path.join("Vande Bharat", 'CAI A improved sealing -2023-14.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2023/14: Improved Sealing Arrangement (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2023/14",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2023',
        "letter_no": "CAI A-2023/14",
    },
    {
        "doc_id": "VB_CAI_Cab_Door_Louvre_DTC_2023",
        "path": os.path.join("Vande Bharat", 'CAI A louvre of cab door in DTC-2023-08.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2023/08: Closing of louvre of cab door in DTC of Vande Bharat, to prevent entry of outside air",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2023/08",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2023',
        "letter_no": "CAI A-2023/08",
    },
    {
        "doc_id": "VB_CAI_Wiper_Assembly_2023",
        "path": os.path.join("Vande Bharat", 'CAI A-issue with wiper assembly 2023-16.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2023/16: Issue with Wiper Assembly (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2023/16",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'electrical',
        "issue_date": '2023',
        "letter_no": "CAI A-2023/16",
    },
    {
        "doc_id": "VB_CAI_Closing_Of_Holes_2023",
        "path": os.path.join("Vande Bharat", 'CAI B 2023 closing of holes-11.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2023/11: Closing of holes around plumbing pipeline in Underframe for modular toilet and pantry equipments",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2023/11",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2023',
        "letter_no": "CAI B-2023/11",
    },
    {
        "doc_id": "VB_CAI_Door_Handle_Set_2023",
        "path": os.path.join("Vande Bharat", 'CAI B door handle set-2023-03.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2023/03: Door handle set & Latch Indicators arrangement replacement work in all lavatory doors",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2023/03",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2023',
        "letter_no": "CAI B-2023/03",
    },
    {
        "doc_id": "VB_CAI_Aux_Compressor_Bracket_2023",
        "path": os.path.join("Vande Bharat", 'CAI for Aux Comp-for Issue.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2023/05: Modification of Auxiliary Compressor Mounting Bracket (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2023/05",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'brakes',
        "issue_date": '2023-04-10',
        "letter_no": "CAI B-2023/05",
    },
    {
        "doc_id": "VB_CAI_Serving_Trolley_Space_2024",
        "path": os.path.join("Vande Bharat", 'CAI A-2024-01.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2024/01: Provision of Space for Parking of Serving Trolley Arrangement (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2024/01",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2024-01-12',
        "letter_no": "CAI A-2024/01",
    },
    {
        "doc_id": "VB_CAI_Prefilter_2024",
        "path": os.path.join("Vande Bharat", 'CAI A inclusion of pre-filter-2024-02.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2024/02: Inclusion of pre filter in Vande Bharat Pantry",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2024/02",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'HVAC',
        "issue_date": '2024',
        "letter_no": "CAI A-2024/02",
    },
    {
        "doc_id": "VB_CAI_Plumbing_Isolating_Cock_2024",
        "path": os.path.join("Vande Bharat", 'CAI isolating cock in plumbing lines A-2024-04.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2024/04: Provision of isolation cock in plumbing lines of FRP modular toilet.",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2024/04",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2024',
        "letter_no": "CAI A-2024/04",
    },
    {
        "doc_id": "VB_CAI_Polycarbonate_Glass_2024",
        "path": os.path.join("Vande Bharat", 'CAI B change of fix polycarbonate glass-2024-05.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/05: Change of fixed polycarbonate glass to Hinged glass door for Fire extinguisher.",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/05",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/05",
    },
    {
        "doc_id": "VB_CAI_Emergency_Hammer_Acrylic_2024",
        "path": os.path.join("Vande Bharat", 'Acrylic sheet for energency hammer CAI B-2024-06.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/06: Acrylic Sheet for Emergency Hammer (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/06",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/06",
    },
    {
        "doc_id": "VB_CAI_Additional_Lifting_Pad_2024",
        "path": os.path.join("Vande Bharat", 'CAI B-Additional lifting pad 2024-07.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/07: Additional Lifting Pad (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/07",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": '',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/07",
    },
    {
        "doc_id": "VB_CAI_Modified_Door_Assembly_2024",
        "path": os.path.join("Vande Bharat", 'Replacement of existing door with modified door assembly CAI B-2024-10.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/10: Replacement of existing door with modified door assembly with louver in Trainset coaches",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/10",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/10",
    },
    {
        "doc_id": "VB_CAI_Driver_Seat_Fixing_2024",
        "path": os.path.join("Vande Bharat", 'Modified fixing arrangement of driver seat CAI B-2024-11.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/11: Modified fixing arrangement of Driver seat (For Retro fitment)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/11",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/11",
    },
    {
        "doc_id": "VB_CAI_Sliding_Ramp_Assembly_2024",
        "path": os.path.join("Vande Bharat", 'CAI B sliding ramp assembly-2024-15.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2024/15: SLIDING RAMP ASSEMBLY FOR WHEEL CHAIR",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2024/15",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2024',
        "letter_no": "CAI B-2024/15",
    },
    {
        "doc_id": "VB_CAI_Wheelchair_Locking_Handle_2025",
        "path": os.path.join("Vande Bharat", 'CAI wheel chair locking handle B-2025-01_acfugrss.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/01: Wheel Chair Locking Handle (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/01",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2025',
        "letter_no": "CAI B-2025/01",
    },
    {
        "doc_id": "VB_CAI_Nose_Cone_Sealing_2025",
        "path": os.path.join("Vande Bharat", 'CAI nose cone sealing A-2025-03_z4qakqja.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2025/03: Nosecone sealing work in DTC of Vande Bharat",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2025/03",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2025',
        "letter_no": "CAI A-2025/03",
    },
    {
        "doc_id": "VB_CAI_Closing_Of_Louvre_2025",
        "path": os.path.join("Vande Bharat", 'CAI closing of louvre A-2025-04_zrqf3mkr.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2025/04: Closing of Louvre (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2025/04",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'HVAC',
        "issue_date": '2025',
        "letter_no": "CAI A-2025/04",
    },
    {
        "doc_id": "VB_CAI_Wash_Basin_Replacement_2025",
        "path": os.path.join("Vande Bharat", 'CAI A-2025-06 replacement of wash basin_ovgz6fa4.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2025/06: 1. Replacement of existing wash basin drain pipe with modified wash basin drain pipe in Trainset coaches",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2025/06",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2025',
        "letter_no": "CAI A-2025/06",
    },
    {
        "doc_id": "VB_CAI_Hatch_Door_2025",
        "path": os.path.join("Vande Bharat", 'CAI B-2025 hatch door-07_6r80y8iz.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/07: Hatch Door (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/07",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2025',
        "letter_no": "CAI B-2025/07",
    },
    {
        "doc_id": "VB_CAI_Duct_Scoop_2025",
        "path": os.path.join("Vande Bharat", 'CAI scoop inside main duct-A-2025-09_85uney8v.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction A-2025/09: Scoop inside Main Duct (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI A-2025/09",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'HVAC',
        "issue_date": '2025',
        "letter_no": "CAI A-2025/09",
    },
    {
        "doc_id": "VB_CAI_Air_Ducts_2025",
        "path": os.path.join("Vande Bharat", 'CAI B-2025-14 (1).pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/14: Modified Supply and Return Air Ducts (uniform cross section) (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/14",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'HVAC',
        "issue_date": '2025-10-16',
        "letter_no": "CAI B-2025/14",
    },
    {
        "doc_id": "VB_CAI_IC_Door_Periphery_Sealing_2025",
        "path": os.path.join("Vande Bharat", 'CAI B-2025-15 (1).pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/15: Sealing Arrangement all around IC Door Periphery in Vande Bharat Chair Car Coaches (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/15",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'doors',
        "issue_date": '2025-10-16',
        "letter_no": "CAI B-2025/15",
    },
    {
        "doc_id": "VB_CAI_Upper_Trim_Panels_2025",
        "path": os.path.join("Vande Bharat", 'CAI B-2025-16 upper trim panels.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/16: Replacement of FRP Upper Trim Panels with Aluminium Upper Trim Panels (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/16",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2025-04-16',
        "letter_no": "CAI B-2025/16",
    },
    {
        "doc_id": "VB_CAI_FRP_Panel_Rectification_2025",
        "path": os.path.join("Vande Bharat", 'CAI B-2025-17 FRP panel rectification.pdf'),
        "doc_type": "coach_alteration_instruction",
        "title": "ICF Coach Alteration Instruction B-2025/17: FRP Panel Rectification / Cleaning (Vande Bharat)",
        "source": "ICF/QMS/MDM/File/F015, CAI B-2025/17",
        "system": "VB",
        "default_oem": None,
        "coach_type": ["Vande Bharat"],
        "subsystem": 'interior fittings',
        "issue_date": '2025',
        "letter_no": "CAI B-2025/17",
    },
]


def full(entry):
    """Entry with all routing/provenance keys present (defaults applied)."""
    return {**_DEFAULTS, **entry}


def pdf_path(entry):
    return os.path.normpath(os.path.join(DOCUMENTS_ROOT, entry["path"]))


def blob_key(entry):
    """Object-storage key for a doc: its Documents-relative path with forward
    slashes (preserves the subfolder structure and keeps keys unique across docs
    that share a basename). Used both to build the URL and by upload_pdfs.py."""
    return entry["path"].replace(os.sep, "/").replace("\\", "/")


def download_url(entry):
    """Public URL of the source PDF, or "" when PDF_BUCKET_BASE is unset. Each
    path segment is URL-encoded (the PDFs have spaces), '/' preserved so the
    bucket mirrors Documents/."""
    if not PDF_BUCKET_BASE:
        return ""
    return f"{PDF_BUCKET_BASE}/{quote(blob_key(entry), safe='/')}"


def by_id(doc_id):
    for e in REGISTRY:
        if e["doc_id"] == doc_id:
            return e
    raise KeyError(f"unknown doc_id: {doc_id}")
